/**
 * models/stations.js
 *
 */
'use strict'

const Sequelize = require('sequelize')

module.exports = (sequelize, DataTypes) => {
  return sequelize.define(
    'stations',
    {
      // pk
      sta_id: {
        type: Sequelize.INTEGER,
         primaryKey: true,
        autoIncrement: true,
        allowNull: false
      },
      sta_name: {
      // Station 2 or Cos Cob
        type: Sequelize.STRING,
        allowNull: false,
        defaultValue: null
      },
      sta_abbr: {
      // STA2
        type: Sequelize.STRING,
        allowNull: false,
        defaultValue: null
      },
      sta_type: {
      // career or volley
        type: Sequelize.STRING,
        allowNull: false,
        defaultValue: null
      },
      sta_gps: {
      // {lat: 0.0, lng: 0.0}
        type: Sequelize.STRING,
        allowNull: false,
        defaultValue: null
      },
      // fk belongs to department
      dept_id: {
        type: Sequelize.INTEGER,
        allowNull: false
      },
      // t/f
      is_enabled: {
        type: Sequelize.BOOLEAN,
        allowNull: false,
        defaultValue: true
      },
      // timestamp generated by sequelize
      created_at: {
        type: Sequelize.DATE,
        allowNull: false
      },
      // timestamp generated by sequelize
      updated_at: {
        type: Sequelize.DATE,
        allowNull: false
      }
    },
    {
      timestamps: true,
      underscored: true,
      getterMethods: {
        id: function () {
          return this.getDataValue('sta_id')
        }
      }
    }
  )
}
